# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in c_day4.gemspec
gemspec

gem "benchmark-ips"
gem "rake", "~> 13.0"
gem "rake-compiler"
gem "rspec", "~> 3.0"
gem "rubocop", "~> 1.21"
gem "solargraph"
