[package]
name = "rs_hello"
version = "0.1.0"
edition = "2021"
authors = ["David Marchante <davidmarchan@gmail.com>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.6.2" }
