# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in rs_day4.gemspec
gemspec

gem "benchmark-ips"
gem "c_day4", path: "../c_day4/"
gem "memory_profiler"
gem "pry"
gem "rake", "~> 13.0"
gem "rake-compiler"
gem "rb_sys", "~> 0.9.63"
gem "rspec", "~> 3.0"
gem "rubocop", "~> 1.21"
gem "solargraph"
