# frozen_string_literal: true

require "bundler/gem_tasks"
require "rspec/core/rake_task"

RSpec::Core::RakeTask.new(:spec)

require "rubocop/rake_task"

RuboCop::RakeTask.new

require "rb_sys/extensiontask"

task build: :compile

GEMSPEC = Gem::Specification.load("rs_day4.gemspec")

RbSys::ExtensionTask.new("rs_day4", GEMSPEC) do |ext|
  ext.lib_dir = "lib/rs_day4"
end

task default: %i[compile spec]
task benchmark: %i[compile] do
  sh "bin/benchmark"
end
